<a href="https://colab.research.google.com/github/Mon6789/Deep-learning-/blob/main/multi_layer_perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ***multi layer perceptron***

In [1]:

import numpy as np

In [2]:
from numpy import argmax

In [3]:
from sklearn.datasets import load_iris

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
from tensorflow.keras.layers import Dense
from tensorflow.keras import Sequential

In [6]:
Iris_data=load_iris()

In [7]:

Iris_data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [8]:
x=Iris_data.data[:,:].astype('float32')

In [10]:
y=Iris_data.target

In [9]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [11]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.10)

In [13]:
N_feature=x_train.shape[1]

In [14]:
N_feature

4

In [16]:
model=Sequential()

In [18]:
model.add(Dense(10,activation='relu',kernel_initializer='he_normal',input_shape=(N_feature,)))
model.add(Dense(8,activation='relu',kernel_initializer='he_normal'))
model.add(Dense(3,activation='softmax'))

In [19]:
model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [20]:
model.fit(x_train,y_train,epochs=100,batch_size=30)

Epoch 1/100
5/5 [==============================] - 1s 6ms/step - loss: 1.1062 - accuracy: 0.3185
Epoch 2/100
5/5 [==============================] - 0s 5ms/step - loss: 1.1028 - accuracy: 0.3185
Epoch 3/100
5/5 [==============================] - 0s 5ms/step - loss: 1.1009 - accuracy: 0.3185
Epoch 4/100
5/5 [==============================] - 0s 4ms/step - loss: 1.1001 - accuracy: 0.3185
Epoch 5/100
5/5 [==============================] - 0s 5ms/step - loss: 1.0988 - accuracy: 0.3185
Epoch 6/100
5/5 [==============================] - 0s 7ms/step - loss: 1.0987 - accuracy: 0.3481
Epoch 7/100
5/5 [==============================] - 0s 5ms/step - loss: 1.0984 - accuracy: 0.3481
Epoch 8/100
5/5 [==============================] - 0s 5ms/step - loss: 1.0982 - accuracy: 0.3481
Epoch 9/100
5/5 [==============================] - 0s 7ms/step - loss: 1.0983 - accuracy: 0.3481
Epoch 10/100
5/5 [==============================] - 0s 5ms/step - loss: 1.0982 - accuracy: 0.3481
Epoch 11/100
5/5 [===========

In [21]:
new_data=[1.5,2.2,0.4,0.5]

In [22]:
y_pred=model.predict([new_data])

1/1 [==============================] - 0s 480ms/step


In [23]:
y_pred

array([[0.8242071 , 0.16195509, 0.01383775]], dtype=float32)

In [24]:
acc_score=model.evaluate(x_test,y_test)

1/1 [==============================] - 0s 202ms/step - loss: 0.1875 - accuracy: 1.0000


In [25]:
acc_score

[0.18745547533035278, 1.0]