<a href="https://colab.research.google.com/github/Mon6789/Deep-learning-/blob/main/sgd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

linear regression fwith SGD

In [ ]:
import numpy as np
from sklearn import linear_model

In [ ]:
rand=np.random.RandomState(0)

In [ ]:
x=rand.randn(16,8)
y=rand.randn(16)

In [ ]:
x

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ,  1.86755799,
        -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351,  0.76103773,
         0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574, -2.55298982,
         0.6536186 ,  0.8644362 , -0.74216502],
       [ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921,
         1.46935877,  0.15494743,  0.37816252],
       [-0.88778575, -1.98079647, -0.34791215,  0.15634897,  1.23029068,
         1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218,
        -0.4380743 , -1.25279536,  0.77749036],
       [-1.61389785, -0.21274028, -0.89546656,  0.3869025 , -0.51080514,
        -1.18063218, -0.02818223,  0.42833187],
       [ 0.06651722,  0.3024719 , -0.63432209, -0.36274117, -0.67246045,
        -0.35955316, -0.81314628, -1.7262826 ],
       [ 0.17742614, -0.40178094

In [ ]:
y

array([ 0.67229476,  0.40746184, -0.76991607,  0.53924919, -0.67433266,
        0.03183056, -0.63584608,  0.67643329,  0.57659082, -0.20829876,
        0.39600671, -1.09306151, -1.49125759,  0.4393917 ,  0.1666735 ,
        0.63503144])

In [ ]:
SGD_Reg=linear_model.SGDRegressor(max_iter=100,penalty='l2',loss='huber',tol=1e-3)

In [ ]:
SGD_Reg.fit(x,y)

SGDRegressor(loss='huber', max_iter=100)

In [ ]:
SGD_Reg.coef_

array([ 0.00499564,  0.00719742, -0.00207933,  0.0090571 ,  0.01600221,
        0.00834482,  0.01208231,  0.00444223])

In [ ]:
SGD_Reg.intercept_

array([0.0087916])